/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c3c0ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#89f5e7",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#0f0069",
        "outline-variant": "#c6c6cd",
        "on-error": "#ffffff",
        background: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        tertiary: "#000000",
        "surface-tint": "#565e74",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#005049",
        "surface-container": "#eceef0",
        outline: "#76777d",
        "on-secondary-fixed-variant": "#3323cc",
        "surface-container-high": "#e6e8ea",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-container": "#0c9488",
        secondary: "#4b41e1",
        "on-secondary-container": "#fffbff",
        primary: "#000000",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed-dim": "#6bd8cb",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#45464d",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-container": "#645efb",
        "secondary-fixed": "#e2dfff",
        surface: "#f7f9fb",
        "on-primary-container": "#7c839b",
        "on-primary": "#ffffff",
        "primary-container": "#131b2e",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "inverse-primary": "#bec6e0",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00201d",
        "on-tertiary-fixed": "#00201d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "80px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        "container-max": "1200px",
        "article-max": "720px",
        xs: "4px",
      },
      fontFamily: {
        "headline-sm": ["Geist", "sans-serif"],
        "body-lg": ["Source Serif 4", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Source Serif 4", "serif"],
      },
      fontSize: {
        "headline-sm": [
          "24px",
          { lineHeight: "1.4", fontWeight: "600" },
        ],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.01em",
            fontWeight: "500",
          },
        ],
        "headline-md": [
          "30px",
          {
            lineHeight: "1.3",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "display-lg-mobile": [
          "36px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-md": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "article-max": "720px",
        "container-max": "1200px",
      },
      keyframes: {
        fadeSlideUp: {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-slide-up": "fadeSlideUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-slide-up-delayed":
          "fadeSlideUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.2s forwards",
        "fade-slide-up-slow":
          "fadeSlideUp 0.8s cubic-bezier(0.16, 1, 0.3, 1) 0.4s forwards",
      },
    },
  },
  plugins: [],
};
